/**
 * MexiChat - Copyright (c) 2024-2026 MexiVanza. All Rights Reserved.
 * Proprietary and confidential. Unauthorized copying, modification,
 * distribution, or use of this software is strictly prohibited.
 * See LICENSE file for details.
 */
/**
 * MexiChat Master Translation File
 * Languages: es (Spanish), en (English), ru (Russian), zh (Chinese)
 */
export type Language = 'es' | 'en' | 'ru' | 'zh';

export interface Translations {
  common: { appName: string; loading: string; save: string; cancel: string; close: string; delete: string; confirm: string; back: string; next: string; search: string; retry: string; error: string; success: string; optional: string; select: string };
  home: { chats: string; groups: string; payments: string; community: string; settings: string };
  landing: {
    nav: { features: string; app: string; privacy: string; download: string; openApp: string };
    hero: { badge: string; line1: string; line2: string; subtitle: string; downloadFree: string; openBrowser: string; e2eEncryption: string; free: string; noAds: string; platforms: string };
    screens: { title: string; subtitle: string };
    features: { title: string; subtitle: string; e2e: { title: string; desc: string }; calls: { title: string; desc: string }; community: { title: string; desc: string }; payments: { title: string; desc: string }; multiplatform: { title: string; desc: string }; biometric: { title: string; desc: string }; oxxo: { title: string; desc: string }; mercadoPago: { title: string; desc: string } };
    privacy: { title: string; desc: string; e2e: string; noTracking: string; noAds: string; noDataSale: string };
    download: { title: string; subtitle: string; android: string; androidReq: string; ios: string; iosReq: string; webApp: string; anyBrowser: string; openWebApp: string; downloadApk: string };
    footer: { tagline: string; app: string; features: string; screenshots: string; download: string; legal: string; privacyPolicy: string; terms: string; community: string; support: string; allRights: string; productOf: string };
    mockChat: { today: string; message: string; online: string; locationShared: string };
  };
  mensajes: { directMessages: string; groups: string; searchChats: string; newChat: string; noMessages: string; searchByUser: string; archived: string; hideArchived: string; typeMessage: string; encryptedNotice: string; deleteConversation: string; deleteConversationDesc: string; leaveGroup: string; leaveGroupDesc: string; deleteGroup: string; deleteGroupDesc: string; kickMember: string; kickMemberDesc: string };
  settings: { title: string; profile: string; privacy: string; security: string; appearance: string; language: string; fullName: string; username: string; phone: string; bio: string; bioPlaceholder: string; nationality: string; gender: string; changeAvatar: string; saving: string; saveChanges: string; signOut: string; lastSeen: string; onlineStatus: string; profilePhoto: string; readReceipts: string; readReceiptsDesc: string; everyone: string; contactsOnly: string; nobody: string; pinLock: string; pinConfigured: string; pinNotConfigured: string; lockNow: string; removePin: string; setupPin: string; e2eEncryption: string; e2eDesc: string; activeSession: string; browser: string; mobile: string; desktop: string; lastActivity: string; twoFactorAuth: string; twoFactorDesc: string; configure2FA: string };
  pagos: { title: string; send: string; history: string; account: string; recipient: string; recipientPlaceholder: string; amount: string; concept: string; conceptPlaceholder: string; paymentMethod: string; mercadoPago: string; oxxo: string; sendAmount: string; processing: string; searchContact: string; minAmount: string; maxAmount: string; maxOxxo: string; selectRecipient: string; loginFirst: string; pending: string; approved: string; rejected: string; linkAccount: string; linkAccountDesc: string; paymentSuccess: string; sendAnother: string; biometricCancelled: string; noTransactions: string };
  seo: { title: string; description: string; keywords: string; ogTitle: string; ogDescription: string };
}

const es: Translations = {
  common: { appName: 'MexiChat', loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', close: 'Cerrar', delete: 'Eliminar', confirm: 'Confirmar', back: 'Volver', next: 'Siguiente', search: 'Buscar', retry: 'Reintentar', error: 'Error', success: 'Exito', optional: 'opcional', select: 'Seleccionar...' },
  home: { chats: 'Chats', groups: 'Grupos', payments: 'Pagos', community: 'Comunidad', settings: 'Ajustes' },
  landing: {
    nav: { features: 'Funciones', app: 'App', privacy: 'Privacidad', download: 'Descargar', openApp: 'Abrir App' },
    hero: { badge: 'Hecho en Mexico para el mundo', line1: 'Tu Mundo,', line2: 'Tu Chat.', subtitle: 'Mensajeria privada con cifrado de extremo a extremo. Llamadas HD, grupos, pagos con Mercado Pago y OXXO, autenticacion biometrica y comunidad â€” todo en una app.', downloadFree: 'Descargar Gratis', openBrowser: 'Abrir en Navegador', e2eEncryption: 'Cifrado E2E', free: 'Gratis', noAds: 'Sin publicidad', platforms: 'Plataformas' },
    screens: { title: 'Conoce MexiChat', subtitle: 'Todo lo que necesitas, en una sola app' },
    features: {
      title: 'Todo lo que necesitas', subtitle: 'Funciones de clase mundial, gratis para todos',
      e2e: { title: 'Cifrado de Extremo a Extremo', desc: 'Todos tus mensajes protegidos con AES-256-GCM y claves ECDH P-256. Nadie mas puede leerlos, ni siquiera nosotros.' },
      calls: { title: 'Llamadas HD', desc: 'Llamadas de voz y video en alta definicion, completamente gratis. Conecta sin importar la distancia.' },
      community: { title: 'Comunidad MexiVanza', desc: 'Red social integrada: comparte contenido, descubre MexiMart, videos y conecta con mexicanos en todo el mundo.' },
      payments: { title: 'Pagos Instantaneos', desc: 'Envia y recibe dinero con Mercado Pago y OXXO directamente desde el chat. Rapido, seguro y sin comisiones ocultas.' },
      multiplatform: { title: 'Multiplataforma', desc: 'Android, iOS y Web. Tus mensajes sincronizados en todos tus dispositivos automaticamente.' },
      biometric: { title: 'Autenticacion Biometrica', desc: 'Protege tu cuenta con Face ID, Touch ID o huella digital. Verificacion biometrica para pagos y acceso a la app.' },
      oxxo: { title: 'Pagos OXXO', desc: 'Paga en cualquier tienda OXXO de Mexico. Genera tu referencia de pago y deposita en efectivo de forma segura.' },
      mercadoPago: { title: 'Mercado Pago', desc: 'Vincula tu cuenta de Mercado Pago para enviar y recibir dinero al instante con la mayor plataforma de pagos de Latinoamerica.' },
    },
    privacy: { title: 'Tu Privacidad, Nuestra Promesa', desc: 'MexiChat fue disenado desde cero con la privacidad como prioridad. Usamos cifrado de extremo a extremo en todos los mensajes y llamadas. No leemos tus chats, no vendemos tus datos, no mostramos publicidad.', e2e: 'Cifrado E2E', noTracking: 'Sin rastreo', noAds: 'Sin publicidad', noDataSale: 'Sin venta de datos' },
    download: { title: 'Descarga MexiChat Gratis', subtitle: 'Disponible para todos tus dispositivos', android: 'Android', androidReq: 'Android 8.0+', ios: 'iOS', iosReq: 'iPhone con iOS 15+', webApp: 'Web App', anyBrowser: 'Cualquier navegador', openWebApp: 'Abrir Web App', downloadApk: 'Descargar APK directamente' },
    footer: { tagline: 'La mensajeria de Mexico para el mundo. Privada, segura, y siempre gratuita.', app: 'App', features: 'Funciones', screenshots: 'Capturas', download: 'Descargar', legal: 'Legal', privacyPolicy: 'Politica de Privacidad', terms: 'Terminos de Servicio', community: 'Comunidad', support: 'Soporte', allRights: 'Todos los derechos reservados.', productOf: 'Un producto de' },
    mockChat: { today: 'Hoy', message: 'Mensaje...', online: 'en linea', locationShared: 'Ubicacion compartida' },
  },
  mensajes: { directMessages: 'MENSAJES DIRECTOS', groups: 'Grupos', searchChats: 'Buscar chats...', newChat: 'Nuevo Chat', noMessages: 'Sin mensajes', searchByUser: 'Buscar por @usuario, nombre o telefono...', archived: 'Archivados', hideArchived: 'Ocultar archivados', typeMessage: 'Escribe un mensaje...', encryptedNotice: 'Tus mensajes privados estan cifrados. Solo tu y el destinatario pueden leerlos.', deleteConversation: 'Eliminar conversacion', deleteConversationDesc: 'Se eliminaran todos los mensajes de esta conversacion. Esta accion no se puede deshacer.', leaveGroup: 'Salir del grupo', leaveGroupDesc: 'Dejaras de recibir mensajes de este grupo.', deleteGroup: 'Eliminar grupo', deleteGroupDesc: 'Se eliminara el grupo y todos sus mensajes permanentemente.', kickMember: 'Expulsar miembro', kickMemberDesc: 'Este usuario sera removido del grupo.' },
  settings: { title: 'Configuracion', profile: 'Perfil', privacy: 'Privacidad', security: 'Seguridad', appearance: 'Apariencia', language: 'Idioma', fullName: 'Nombre completo', username: 'Nombre de usuario', phone: 'Telefono', bio: 'Bio', bioPlaceholder: 'Escribe algo sobre ti...', nationality: 'Nacionalidad', gender: 'Genero', changeAvatar: 'Toca el icono para cambiar tu foto', saving: 'Guardando...', saveChanges: 'Guardar Cambios', signOut: 'Cerrar sesion', lastSeen: 'Ultima vez visto', onlineStatus: 'Estado en linea', profilePhoto: 'Foto de perfil', readReceipts: 'Confirmaciones de lectura', readReceiptsDesc: 'Mostrar palomitas azules cuando leas mensajes', everyone: 'Todos', contactsOnly: 'Solo contactos', nobody: 'Nadie', pinLock: 'Bloqueo con PIN', pinConfigured: 'PIN configurado. Tus chats estan protegidos.', pinNotConfigured: 'Protege tus chats con un PIN de acceso.', lockNow: 'Bloquear ahora', removePin: 'Eliminar PIN', setupPin: 'Configurar PIN', e2eEncryption: 'Cifrado de extremo a extremo', e2eDesc: 'Tus mensajes privados estan cifrados. Solo tu y el destinatario pueden leerlos.', activeSession: 'Sesion activa', browser: 'Navegador', mobile: 'Movil', desktop: 'Escritorio', lastActivity: 'Ultima actividad', twoFactorAuth: 'Autenticacion de dos factores', twoFactorDesc: 'Protege tu cuenta con una app de autenticacion', configure2FA: 'Configurar 2FA' },
  pagos: { title: 'Pagos', send: 'Enviar', history: 'Historial', account: 'Cuenta', recipient: 'Destinatario', recipientPlaceholder: 'UUID del destinatario', amount: 'Monto (MXN)', concept: 'Concepto (opcional)', conceptPlaceholder: 'Ej: Pago de comida', paymentMethod: 'Metodo de pago', mercadoPago: 'Mercado Pago', oxxo: 'OXXO', sendAmount: 'Enviar', processing: 'Procesando...', searchContact: 'Buscar por nombre, @usuario o telefono...', minAmount: 'Monto minimo: $10 MXN', maxAmount: 'Monto maximo: $500,000 MXN', maxOxxo: 'Monto maximo para OXXO: $10,000 MXN', selectRecipient: 'Selecciona un destinatario', loginFirst: 'Inicia sesion primero', pending: 'Pendiente', approved: 'Aprobado', rejected: 'Rechazado', linkAccount: 'Vincula tu cuenta', linkAccountDesc: 'Vincula tu cuenta para enviar y recibir pagos', paymentSuccess: 'Pago exitoso', sendAnother: 'Enviar otro pago', biometricCancelled: 'Verificacion biometrica cancelada', noTransactions: 'No hay transacciones aun' },
  seo: { title: 'MexiChat - Mensajeria Segura con Pagos, Biometria y Comunidad', description: 'Mensajeria privada con cifrado E2E, llamadas HD, pagos con Mercado Pago y OXXO, autenticacion biometrica (Face ID, huella digital), grupos y comunidad MexiVanza. Gratis.', keywords: 'mexichat, mensajeria segura, chat privado, pagos mercado pago, pagos oxxo, autenticacion biometrica, face id, huella digital, cifrado extremo a extremo, mexivanza, comunidad mexicana, alternativa whatsapp', ogTitle: 'MexiChat - Mensajeria Privada con Pagos y Biometria', ogDescription: 'Chat cifrado E2E, llamadas HD, pagos Mercado Pago/OXXO, Face ID/huella digital, comunidad MexiVanza. Gratis.' },
};
const en: Translations = {
  common: { appName: 'MexiChat', loading: 'Loading...', save: 'Save', cancel: 'Cancel', close: 'Close', delete: 'Delete', confirm: 'Confirm', back: 'Back', next: 'Next', search: 'Search', retry: 'Retry', error: 'Error', success: 'Success', optional: 'optional', select: 'Select...' },
  home: { chats: 'Chats', groups: 'Groups', payments: 'Payments', community: 'Community', settings: 'Settings' },
  landing: {
    nav: { features: 'Features', app: 'App', privacy: 'Privacy', download: 'Download', openApp: 'Open App' },
    hero: { badge: 'Made in Mexico for the world', line1: 'Your World,', line2: 'Your Chat.', subtitle: 'Private messaging with end-to-end encryption. HD calls, groups, payments via Mercado Pago & OXXO, biometric authentication, and community â€” all in one app.', downloadFree: 'Download Free', openBrowser: 'Open in Browser', e2eEncryption: 'E2E Encryption', free: 'Free', noAds: 'No ads', platforms: 'Platforms' },
    screens: { title: 'Discover MexiChat', subtitle: 'Everything you need, in one app' },
    features: {
      title: 'Everything you need', subtitle: 'World-class features, free for everyone',
      e2e: { title: 'End-to-End Encryption', desc: 'All your messages protected with AES-256-GCM and ECDH P-256 keys. No one else can read them, not even us.' },
      calls: { title: 'HD Calls', desc: 'High-definition voice and video calls, completely free. Connect regardless of distance.' },
      community: { title: 'MexiVanza Community', desc: 'Integrated social network: share content, discover MexiMart, videos and connect with Mexicans worldwide.' },
      payments: { title: 'Instant Payments', desc: 'Send and receive money with Mercado Pago and OXXO directly from chat. Fast, secure, and no hidden fees.' },
      multiplatform: { title: 'Multi-platform', desc: 'Android, iOS and Web. Your messages synced across all your devices automatically.' },
      biometric: { title: 'Biometric Authentication', desc: 'Protect your account with Face ID, Touch ID or fingerprint. Biometric verification for payments and app access.' },
      oxxo: { title: 'OXXO Payments', desc: 'Pay at any OXXO store in Mexico. Generate your payment reference and deposit cash securely.' },
      mercadoPago: { title: 'Mercado Pago', desc: 'Link your Mercado Pago account to send and receive money instantly with Latin Americas largest payment platform.' },
    },
    privacy: { title: 'Your Privacy, Our Promise', desc: 'MexiChat was designed from the ground up with privacy as a priority. We use end-to-end encryption for all messages and calls. We do not read your chats, sell your data, or show ads.', e2e: 'E2E Encryption', noTracking: 'No tracking', noAds: 'No ads', noDataSale: 'No data sales' },
    download: { title: 'Download MexiChat Free', subtitle: 'Available for all your devices', android: 'Android', androidReq: 'Android 8.0+', ios: 'iOS', iosReq: 'iPhone with iOS 15+', webApp: 'Web App', anyBrowser: 'Any browser', openWebApp: 'Open Web App', downloadApk: 'Download APK directly' },
    footer: { tagline: 'Mexicos messaging for the world. Private, secure, and always free.', app: 'App', features: 'Features', screenshots: 'Screenshots', download: 'Download', legal: 'Legal', privacyPolicy: 'Privacy Policy', terms: 'Terms of Service', community: 'Community', support: 'Support', allRights: 'All rights reserved.', productOf: 'A product of' },
    mockChat: { today: 'Today', message: 'Message...', online: 'online', locationShared: 'Location shared' },
  },
  mensajes: { directMessages: 'DIRECT MESSAGES', groups: 'Groups', searchChats: 'Search chats...', newChat: 'New Chat', noMessages: 'No messages', searchByUser: 'Search by @username, name or phone...', archived: 'Archived', hideArchived: 'Hide archived', typeMessage: 'Type a message...', encryptedNotice: 'Your private messages are encrypted. Only you and the recipient can read them.', deleteConversation: 'Delete conversation', deleteConversationDesc: 'All messages will be deleted. This cannot be undone.', leaveGroup: 'Leave group', leaveGroupDesc: 'You will stop receiving messages from this group.', deleteGroup: 'Delete group', deleteGroupDesc: 'The group and all messages will be permanently deleted.', kickMember: 'Kick member', kickMemberDesc: 'This user will be removed from the group.' },
  settings: { title: 'Settings', profile: 'Profile', privacy: 'Privacy', security: 'Security', appearance: 'Appearance', language: 'Language', fullName: 'Full name', username: 'Username', phone: 'Phone', bio: 'Bio', bioPlaceholder: 'Write something about yourself...', nationality: 'Nationality', gender: 'Gender', changeAvatar: 'Tap the icon to change your photo', saving: 'Saving...', saveChanges: 'Save Changes', signOut: 'Sign Out', lastSeen: 'Last seen', onlineStatus: 'Online status', profilePhoto: 'Profile photo', readReceipts: 'Read receipts', readReceiptsDesc: 'Show blue checkmarks when you read messages', everyone: 'Everyone', contactsOnly: 'Contacts only', nobody: 'Nobody', pinLock: 'PIN Lock', pinConfigured: 'PIN set. Your chats are protected.', pinNotConfigured: 'Protect your chats with an access PIN.', lockNow: 'Lock now', removePin: 'Remove PIN', setupPin: 'Set up PIN', e2eEncryption: 'End-to-end encryption', e2eDesc: 'Your private messages are encrypted. Only you and the recipient can read them.', activeSession: 'Active session', browser: 'Browser', mobile: 'Mobile', desktop: 'Desktop', lastActivity: 'Last activity', twoFactorAuth: 'Two-factor authentication', twoFactorDesc: 'Protect your account with an authenticator app', configure2FA: 'Set up 2FA' },
  pagos: { title: 'Payments', send: 'Send', history: 'History', account: 'Account', recipient: 'Recipient', recipientPlaceholder: 'Recipient UUID', amount: 'Amount (MXN)', concept: 'Concept (optional)', conceptPlaceholder: 'e.g. Lunch payment', paymentMethod: 'Payment method', mercadoPago: 'Mercado Pago', oxxo: 'OXXO', sendAmount: 'Send', processing: 'Processing...', searchContact: 'Search by name, @username or phone...', minAmount: 'Minimum: $10 MXN', maxAmount: 'Maximum: $500,000 MXN', maxOxxo: 'Max for OXXO: $10,000 MXN', selectRecipient: 'Select a recipient', loginFirst: 'Please sign in first', pending: 'Pending', approved: 'Approved', rejected: 'Rejected', linkAccount: 'Link your account', linkAccountDesc: 'Link your account to send and receive payments', paymentSuccess: 'Payment successful', sendAnother: 'Send another payment', biometricCancelled: 'Biometric verification cancelled', noTransactions: 'No transactions yet' },
  seo: { title: 'MexiChat - Secure Messaging with Payments, Biometrics & Community', description: 'Private messaging with E2E encryption, HD calls, Mercado Pago & OXXO payments, biometric auth (Face ID, fingerprint), groups and MexiVanza community. Free.', keywords: 'mexichat, secure messaging, private chat, mercado pago, oxxo payments, biometric authentication, face id, fingerprint, end-to-end encryption, mexivanza, whatsapp alternative', ogTitle: 'MexiChat - Private Messaging with Payments & Biometrics', ogDescription: 'E2E encrypted chat, HD calls, Mercado Pago/OXXO payments, Face ID/fingerprint, MexiVanza community. Free.' },
};
const ru: Translations = {
  common: { appName: 'MexiChat', loading: 'Ð—Ð°Ð³Ñ€ÑƒÐ·ÐºÐ°...', save: 'Ð¡Ð¾Ñ…Ñ€Ð°Ð½Ð¸Ñ‚ÑŒ', cancel: 'ÐžÑ‚Ð¼ÐµÐ½Ð°', close: 'Ð—Ð°ÐºÑ€Ñ‹Ñ‚ÑŒ', delete: 'Ð£Ð´Ð°Ð»Ð¸Ñ‚ÑŒ', confirm: 'ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ', back: 'ÐÐ°Ð·Ð°Ð´', next: 'Ð”Ð°Ð»ÐµÐµ', search: 'ÐŸÐ¾Ð¸ÑÐº', retry: 'ÐŸÐ¾Ð²Ñ‚Ð¾Ñ€Ð¸Ñ‚ÑŒ', error: 'ÐžÑˆÐ¸Ð±ÐºÐ°', success: 'Ð£ÑÐ¿ÐµÑˆÐ½Ð¾', optional: 'Ð½ÐµÐ¾Ð±ÑÐ·Ð°Ñ‚ÐµÐ»ÑŒÐ½Ð¾', select: 'Ð’Ñ‹Ð±Ñ€Ð°Ñ‚ÑŒ...' },
  home: { chats: 'Ð§Ð°Ñ‚Ñ‹', groups: 'Ð“Ñ€ÑƒÐ¿Ð¿Ñ‹', payments: 'ÐŸÐ»Ð°Ñ‚ÐµÐ¶Ð¸', community: 'Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÑÑ‚Ð²Ð¾', settings: 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸' },
  landing: {
    nav: { features: 'Ð¤ÑƒÐ½ÐºÑ†Ð¸Ð¸', app: 'ÐŸÑ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ', privacy: 'ÐšÐ¾Ð½Ñ„Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚ÑŒ', download: 'Ð¡ÐºÐ°Ñ‡Ð°Ñ‚ÑŒ', openApp: 'ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ' },
    hero: { badge: 'Ð¡Ð´ÐµÐ»Ð°Ð½Ð¾ Ð² ÐœÐµÐºÑÐ¸ÐºÐµ Ð´Ð»Ñ Ð¼Ð¸Ñ€Ð°', line1: 'Ð¢Ð²Ð¾Ð¹ ÐœÐ¸Ñ€,', line2: 'Ð¢Ð²Ð¾Ð¹ Ð§Ð°Ñ‚.', subtitle: 'ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ð°Ñ Ð¿ÐµÑ€ÐµÐ¿Ð¸ÑÐºÐ° ÑÐ¾ ÑÐºÐ²Ð¾Ð·Ð½Ñ‹Ð¼ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸ÐµÐ¼. HD-Ð·Ð²Ð¾Ð½ÐºÐ¸, Ð³Ñ€ÑƒÐ¿Ð¿Ñ‹, Ð¿Ð»Ð°Ñ‚ÐµÐ¶Ð¸ Mercado Pago Ð¸ OXXO, Ð±Ð¸Ð¾Ð¼ÐµÑ‚Ñ€Ð¸Ñ Ð¸ ÑÐ¾Ð¾Ð±Ñ‰ÐµÑÑ‚Ð²Ð¾ â€” Ð²ÑÑ‘ Ð² Ð¾Ð´Ð½Ð¾Ð¼.', downloadFree: 'Ð¡ÐºÐ°Ñ‡Ð°Ñ‚ÑŒ Ð±ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾', openBrowser: 'ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ Ð² Ð±Ñ€Ð°ÑƒÐ·ÐµÑ€Ðµ', e2eEncryption: 'Ð¡ÐºÐ²Ð¾Ð·Ð½Ð¾Ðµ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ', free: 'Ð‘ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾', noAds: 'Ð‘ÐµÐ· Ñ€ÐµÐºÐ»Ð°Ð¼Ñ‹', platforms: 'ÐŸÐ»Ð°Ñ‚Ñ„Ð¾Ñ€Ð¼Ñ‹' },
    screens: { title: 'Ð—Ð½Ð°ÐºÐ¾Ð¼ÑŒÑ‚ÐµÑÑŒ Ñ MexiChat', subtitle: 'Ð’ÑÑ‘ Ñ‡Ñ‚Ð¾ Ð½ÑƒÐ¶Ð½Ð¾, Ð² Ð¾Ð´Ð½Ð¾Ð¼ Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ð¸' },
    features: {
      title: 'Ð’ÑÑ‘ Ñ‡Ñ‚Ð¾ Ð²Ð°Ð¼ Ð½ÑƒÐ¶Ð½Ð¾', subtitle: 'Ð¤ÑƒÐ½ÐºÑ†Ð¸Ð¸ Ð¼Ð¸Ñ€Ð¾Ð²Ð¾Ð³Ð¾ ÐºÐ»Ð°ÑÑÐ°, Ð±ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾ Ð´Ð»Ñ Ð²ÑÐµÑ…',
      e2e: { title: 'Ð¡ÐºÐ²Ð¾Ð·Ð½Ð¾Ðµ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ', desc: 'Ð’ÑÐµ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ Ð·Ð°Ñ‰Ð¸Ñ‰ÐµÐ½Ñ‹ AES-256-GCM Ð¸ ÐºÐ»ÑŽÑ‡Ð°Ð¼Ð¸ ECDH P-256. ÐÐ¸ÐºÑ‚Ð¾ Ð½Ðµ Ð¼Ð¾Ð¶ÐµÑ‚ Ð¸Ñ… Ð¿Ñ€Ð¾Ñ‡Ð¸Ñ‚Ð°Ñ‚ÑŒ, Ð´Ð°Ð¶Ðµ Ð¼Ñ‹.' },
      calls: { title: 'HD Ð—Ð²Ð¾Ð½ÐºÐ¸', desc: 'Ð“Ð¾Ð»Ð¾ÑÐ¾Ð²Ñ‹Ðµ Ð¸ Ð²Ð¸Ð´ÐµÐ¾Ð·Ð²Ð¾Ð½ÐºÐ¸ Ð²Ñ‹ÑÐ¾ÐºÐ¾Ð³Ð¾ ÐºÐ°Ñ‡ÐµÑÑ‚Ð²Ð°, ÑÐ¾Ð²ÐµÑ€ÑˆÐµÐ½Ð½Ð¾ Ð±ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾.' },
      community: { title: 'Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÑÑ‚Ð²Ð¾ MexiVanza', desc: 'Ð’ÑÑ‚Ñ€Ð¾ÐµÐ½Ð½Ð°Ñ ÑÐ¾Ñ†ÑÐµÑ‚ÑŒ: ÐºÐ¾Ð½Ñ‚ÐµÐ½Ñ‚, MexiMart, Ð²Ð¸Ð´ÐµÐ¾ Ð¸ Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ðµ Ñ Ð¼ÐµÐºÑÐ¸ÐºÐ°Ð½Ñ†Ð°Ð¼Ð¸ Ð¿Ð¾ Ð²ÑÐµÐ¼Ñƒ Ð¼Ð¸Ñ€Ñƒ.' },
      payments: { title: 'ÐœÐ³Ð½Ð¾Ð²ÐµÐ½Ð½Ñ‹Ðµ Ð¿Ð»Ð°Ñ‚ÐµÐ¶Ð¸', desc: 'ÐžÑ‚Ð¿Ñ€Ð°Ð²Ð»ÑÐ¹Ñ‚Ðµ Ð´ÐµÐ½ÑŒÐ³Ð¸ Ñ‡ÐµÑ€ÐµÐ· Mercado Pago Ð¸ OXXO Ð¿Ñ€ÑÐ¼Ð¾ Ð¸Ð· Ñ‡Ð°Ñ‚Ð°. Ð‘Ñ‹ÑÑ‚Ñ€Ð¾ Ð¸ Ð±ÐµÐ·Ð¾Ð¿Ð°ÑÐ½Ð¾.' },
      multiplatform: { title: 'ÐœÑƒÐ»ÑŒÑ‚Ð¸Ð¿Ð»Ð°Ñ‚Ñ„Ð¾Ñ€Ð¼Ð°', desc: 'Android, iOS Ð¸ Web. Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ ÑÐ¸Ð½Ñ…Ñ€Ð¾Ð½Ð¸Ð·Ð¸Ñ€ÑƒÑŽÑ‚ÑÑ Ð½Ð° Ð²ÑÐµÑ… ÑƒÑÑ‚Ñ€Ð¾Ð¹ÑÑ‚Ð²Ð°Ñ….' },
      biometric: { title: 'Ð‘Ð¸Ð¾Ð¼ÐµÑ‚Ñ€Ð¸Ñ‡ÐµÑÐºÐ°Ñ Ð°ÑƒÑ‚ÐµÐ½Ñ‚Ð¸Ñ„Ð¸ÐºÐ°Ñ†Ð¸Ñ', desc: 'Ð—Ð°Ñ‰Ð¸Ñ‚Ð¸Ñ‚Ðµ Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚ Ñ Face ID, Touch ID Ð¸Ð»Ð¸ Ð¾Ñ‚Ð¿ÐµÑ‡Ð°Ñ‚ÐºÐ¾Ð¼ Ð¿Ð°Ð»ÑŒÑ†Ð°.' },
      oxxo: { title: 'ÐŸÐ»Ð°Ñ‚ÐµÐ¶Ð¸ OXXO', desc: 'ÐžÐ¿Ð»Ð°Ñ‚Ð° Ð² Ð»ÑŽÐ±Ð¾Ð¼ Ð¼Ð°Ð³Ð°Ð·Ð¸Ð½Ðµ OXXO Ð² ÐœÐµÐºÑÐ¸ÐºÐµ Ð½Ð°Ð»Ð¸Ñ‡Ð½Ñ‹Ð¼Ð¸.' },
      mercadoPago: { title: 'Mercado Pago', desc: 'ÐŸÑ€Ð¸Ð²ÑÐ¶Ð¸Ñ‚Ðµ Mercado Pago Ð´Ð»Ñ Ð¼Ð³Ð½Ð¾Ð²ÐµÐ½Ð½Ñ‹Ñ… Ð¿ÐµÑ€ÐµÐ²Ð¾Ð´Ð¾Ð² Ñ‡ÐµÑ€ÐµÐ· ÐºÑ€ÑƒÐ¿Ð½ÐµÐ¹ÑˆÑƒÑŽ Ð¿Ð»Ð°Ñ‚Ñ„Ð¾Ñ€Ð¼Ñƒ Ð›Ð°Ñ‚Ð¸Ð½ÑÐºÐ¾Ð¹ ÐÐ¼ÐµÑ€Ð¸ÐºÐ¸.' },
    },
    privacy: { title: 'Ð’Ð°ÑˆÐ° ÐºÐ¾Ð½Ñ„Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚ÑŒ â€” Ð½Ð°ÑˆÐµ Ð¾Ð±ÐµÑ‰Ð°Ð½Ð¸Ðµ', desc: 'MexiChat ÑÐ¾Ð·Ð´Ð°Ð½ Ñ Ð¿Ñ€Ð¸Ð¾Ñ€Ð¸Ñ‚ÐµÑ‚Ð¾Ð¼ ÐºÐ¾Ð½Ñ„Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚Ð¸. Ð¡ÐºÐ²Ð¾Ð·Ð½Ð¾Ðµ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ Ð´Ð»Ñ Ð²ÑÐµÑ… ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ð¹ Ð¸ Ð·Ð²Ð¾Ð½ÐºÐ¾Ð². ÐœÑ‹ Ð½Ðµ Ñ‡Ð¸Ñ‚Ð°ÐµÐ¼ Ñ‡Ð°Ñ‚Ñ‹, Ð½Ðµ Ð¿Ñ€Ð¾Ð´Ð°Ñ‘Ð¼ Ð´Ð°Ð½Ð½Ñ‹Ðµ, Ð½Ðµ Ð¿Ð¾ÐºÐ°Ð·Ñ‹Ð²Ð°ÐµÐ¼ Ñ€ÐµÐºÐ»Ð°Ð¼Ñƒ.', e2e: 'Ð¡ÐºÐ²Ð¾Ð·Ð½Ð¾Ðµ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ', noTracking: 'Ð‘ÐµÐ· ÑÐ»ÐµÐ¶ÐºÐ¸', noAds: 'Ð‘ÐµÐ· Ñ€ÐµÐºÐ»Ð°Ð¼Ñ‹', noDataSale: 'Ð‘ÐµÐ· Ð¿Ñ€Ð¾Ð´Ð°Ð¶Ð¸ Ð´Ð°Ð½Ð½Ñ‹Ñ…' },
    download: { title: 'Ð¡ÐºÐ°Ñ‡Ð°Ð¹Ñ‚Ðµ MexiChat Ð±ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾', subtitle: 'Ð”Ð»Ñ Ð²ÑÐµÑ… ÑƒÑÑ‚Ñ€Ð¾Ð¹ÑÑ‚Ð²', android: 'Android', androidReq: 'Android 8.0+', ios: 'iOS', iosReq: 'iPhone Ñ iOS 15+', webApp: 'Ð’ÐµÐ±-Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ', anyBrowser: 'Ð›ÑŽÐ±Ð¾Ð¹ Ð±Ñ€Ð°ÑƒÐ·ÐµÑ€', openWebApp: 'ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ Ð²ÐµÐ±-Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ', downloadApk: 'Ð¡ÐºÐ°Ñ‡Ð°Ñ‚ÑŒ APK' },
    footer: { tagline: 'ÐœÐµÐºÑÐ¸ÐºÐ°Ð½ÑÐºÐ¸Ð¹ Ð¼ÐµÑÑÐµÐ½Ð´Ð¶ÐµÑ€ Ð´Ð»Ñ Ð¼Ð¸Ñ€Ð°. ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ð¹, Ð±ÐµÐ·Ð¾Ð¿Ð°ÑÐ½Ñ‹Ð¹, Ð±ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ñ‹Ð¹.', app: 'ÐŸÑ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ', features: 'Ð¤ÑƒÐ½ÐºÑ†Ð¸Ð¸', screenshots: 'Ð¡ÐºÑ€Ð¸Ð½ÑˆÐ¾Ñ‚Ñ‹', download: 'Ð¡ÐºÐ°Ñ‡Ð°Ñ‚ÑŒ', legal: 'ÐŸÑ€Ð°Ð²Ð¾Ð²Ð°Ñ Ð¸Ð½Ñ„Ð¾Ñ€Ð¼Ð°Ñ†Ð¸Ñ', privacyPolicy: 'ÐŸÐ¾Ð»Ð¸Ñ‚Ð¸ÐºÐ° ÐºÐ¾Ð½Ñ„Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚Ð¸', terms: 'Ð£ÑÐ»Ð¾Ð²Ð¸Ñ Ð¸ÑÐ¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ð½Ð¸Ñ', community: 'Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÑÑ‚Ð²Ð¾', support: 'ÐŸÐ¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ°', allRights: 'Ð’ÑÐµ Ð¿Ñ€Ð°Ð²Ð° Ð·Ð°Ñ‰Ð¸Ñ‰ÐµÐ½Ñ‹.', productOf: 'ÐŸÑ€Ð¾Ð´ÑƒÐºÑ‚' },
    mockChat: { today: 'Ð¡ÐµÐ³Ð¾Ð´Ð½Ñ', message: 'Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ðµ...', online: 'Ð² ÑÐµÑ‚Ð¸', locationShared: 'Ð“ÐµÐ¾Ð»Ð¾ÐºÐ°Ñ†Ð¸Ñ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð»ÐµÐ½Ð°' },
  },
  mensajes: { directMessages: 'Ð›Ð˜Ð§ÐÐ«Ð• Ð¡ÐžÐžÐ‘Ð©Ð•ÐÐ˜Ð¯', groups: 'Ð“Ñ€ÑƒÐ¿Ð¿Ñ‹', searchChats: 'ÐŸÐ¾Ð¸ÑÐº Ñ‡Ð°Ñ‚Ð¾Ð²...', newChat: 'ÐÐ¾Ð²Ñ‹Ð¹ Ñ‡Ð°Ñ‚', noMessages: 'ÐÐµÑ‚ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ð¹', searchByUser: 'ÐŸÐ¾Ð¸ÑÐº Ð¿Ð¾ @Ð¸Ð¼ÐµÐ½Ð¸ Ð¸Ð»Ð¸ Ñ‚ÐµÐ»ÐµÑ„Ð¾Ð½Ñƒ...', archived: 'ÐÑ€Ñ…Ð¸Ð²', hideArchived: 'Ð¡ÐºÑ€Ñ‹Ñ‚ÑŒ Ð°Ñ€Ñ…Ð¸Ð²', typeMessage: 'Ð’Ð²ÐµÐ´Ð¸Ñ‚Ðµ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ðµ...', encryptedNotice: 'Ð’Ð°ÑˆÐ¸ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ Ð·Ð°ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ñ‹. Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð²Ñ‹ Ð¸ Ð¿Ð¾Ð»ÑƒÑ‡Ð°Ñ‚ÐµÐ»ÑŒ Ð¼Ð¾Ð¶ÐµÑ‚Ðµ Ð¸Ñ… Ð¿Ñ€Ð¾Ñ‡Ð¸Ñ‚Ð°Ñ‚ÑŒ.', deleteConversation: 'Ð£Ð´Ð°Ð»Ð¸Ñ‚ÑŒ Ñ€Ð°Ð·Ð³Ð¾Ð²Ð¾Ñ€', deleteConversationDesc: 'Ð’ÑÐµ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ Ð±ÑƒÐ´ÑƒÑ‚ ÑƒÐ´Ð°Ð»ÐµÐ½Ñ‹. ÐžÑ‚Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ð½ÐµÐ»ÑŒÐ·Ñ.', leaveGroup: 'ÐŸÐ¾ÐºÐ¸Ð½ÑƒÑ‚ÑŒ Ð³Ñ€ÑƒÐ¿Ð¿Ñƒ', leaveGroupDesc: 'Ð’Ñ‹ Ð¿ÐµÑ€ÐµÑÑ‚Ð°Ð½ÐµÑ‚Ðµ Ð¿Ð¾Ð»ÑƒÑ‡Ð°Ñ‚ÑŒ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ.', deleteGroup: 'Ð£Ð´Ð°Ð»Ð¸Ñ‚ÑŒ Ð³Ñ€ÑƒÐ¿Ð¿Ñƒ', deleteGroupDesc: 'Ð“Ñ€ÑƒÐ¿Ð¿Ð° Ð¸ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ Ð±ÑƒÐ´ÑƒÑ‚ ÑƒÐ´Ð°Ð»ÐµÐ½Ñ‹ Ð½Ð°Ð²ÑÐµÐ³Ð´Ð°.', kickMember: 'Ð˜ÑÐºÐ»ÑŽÑ‡Ð¸Ñ‚ÑŒ ÑƒÑ‡Ð°ÑÑ‚Ð½Ð¸ÐºÐ°', kickMemberDesc: 'ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒ Ð±ÑƒÐ´ÐµÑ‚ ÑƒÐ´Ð°Ð»Ñ‘Ð½ Ð¸Ð· Ð³Ñ€ÑƒÐ¿Ð¿Ñ‹.' },
  settings: { title: 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸', profile: 'ÐŸÑ€Ð¾Ñ„Ð¸Ð»ÑŒ', privacy: 'ÐšÐ¾Ð½Ñ„Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚ÑŒ', security: 'Ð‘ÐµÐ·Ð¾Ð¿Ð°ÑÐ½Ð¾ÑÑ‚ÑŒ', appearance: 'Ð’Ð½ÐµÑˆÐ½Ð¸Ð¹ Ð²Ð¸Ð´', language: 'Ð¯Ð·Ñ‹Ðº', fullName: 'ÐŸÐ¾Ð»Ð½Ð¾Ðµ Ð¸Ð¼Ñ', username: 'Ð˜Ð¼Ñ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ', phone: 'Ð¢ÐµÐ»ÐµÑ„Ð¾Ð½', bio: 'Ðž ÑÐµÐ±Ðµ', bioPlaceholder: 'ÐÐ°Ð¿Ð¸ÑˆÐ¸Ñ‚Ðµ Ð¾ ÑÐµÐ±Ðµ...', nationality: 'ÐÐ°Ñ†Ð¸Ð¾Ð½Ð°Ð»ÑŒÐ½Ð¾ÑÑ‚ÑŒ', gender: 'ÐŸÐ¾Ð»', changeAvatar: 'ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ Ð´Ð»Ñ ÑÐ¼ÐµÐ½Ñ‹ Ñ„Ð¾Ñ‚Ð¾', saving: 'Ð¡Ð¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ð¸Ðµ...', saveChanges: 'Ð¡Ð¾Ñ…Ñ€Ð°Ð½Ð¸Ñ‚ÑŒ', signOut: 'Ð’Ñ‹Ð¹Ñ‚Ð¸', lastSeen: 'ÐŸÐ¾ÑÐ»ÐµÐ´Ð½Ð¸Ð¹ Ð²Ð¸Ð·Ð¸Ñ‚', onlineStatus: 'Ð¡Ñ‚Ð°Ñ‚ÑƒÑ Ð¾Ð½Ð»Ð°Ð¹Ð½', profilePhoto: 'Ð¤Ð¾Ñ‚Ð¾ Ð¿Ñ€Ð¾Ñ„Ð¸Ð»Ñ', readReceipts: 'ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð¶Ð´ÐµÐ½Ð¸Ñ Ð¿Ñ€Ð¾Ñ‡Ñ‚ÐµÐ½Ð¸Ñ', readReceiptsDesc: 'Ð¡Ð¸Ð½Ð¸Ðµ Ð³Ð°Ð»Ð¾Ñ‡ÐºÐ¸ Ð¿Ñ€Ð¸ Ð¿Ñ€Ð¾Ñ‡Ñ‚ÐµÐ½Ð¸Ð¸', everyone: 'Ð’ÑÐµ', contactsOnly: 'Ð¢Ð¾Ð»ÑŒÐºÐ¾ ÐºÐ¾Ð½Ñ‚Ð°ÐºÑ‚Ñ‹', nobody: 'ÐÐ¸ÐºÑ‚Ð¾', pinLock: 'Ð‘Ð»Ð¾ÐºÐ¸Ñ€Ð¾Ð²ÐºÐ° PIN', pinConfigured: 'PIN ÑƒÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½. Ð§Ð°Ñ‚Ñ‹ Ð·Ð°Ñ‰Ð¸Ñ‰ÐµÐ½Ñ‹.', pinNotConfigured: 'Ð—Ð°Ñ‰Ð¸Ñ‚Ð¸Ñ‚Ðµ Ñ‡Ð°Ñ‚Ñ‹ PIN-ÐºÐ¾Ð´Ð¾Ð¼.', lockNow: 'Ð—Ð°Ð±Ð»Ð¾ÐºÐ¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ', removePin: 'Ð£Ð´Ð°Ð»Ð¸Ñ‚ÑŒ PIN', setupPin: 'Ð£ÑÑ‚Ð°Ð½Ð¾Ð²Ð¸Ñ‚ÑŒ PIN', e2eEncryption: 'Ð¡ÐºÐ²Ð¾Ð·Ð½Ð¾Ðµ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ', e2eDesc: 'Ð¡Ð¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ñ Ð·Ð°ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ñ‹. Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð²Ñ‹ Ð¸ Ð¿Ð¾Ð»ÑƒÑ‡Ð°Ñ‚ÐµÐ»ÑŒ Ð¼Ð¾Ð¶ÐµÑ‚Ðµ Ð¸Ñ… Ñ‡Ð¸Ñ‚Ð°Ñ‚ÑŒ.', activeSession: 'ÐÐºÑ‚Ð¸Ð²Ð½Ð°Ñ ÑÐµÑÑÐ¸Ñ', browser: 'Ð‘Ñ€Ð°ÑƒÐ·ÐµÑ€', mobile: 'ÐœÐ¾Ð±Ð¸Ð»ÑŒÐ½Ñ‹Ð¹', desktop: 'ÐšÐ¾Ð¼Ð¿ï¿½ï¿½ÑŽÑ‚ÐµÑ€', lastActivity: 'ÐŸÐ¾ÑÐ»ÐµÐ´Ð½ÑÑ Ð°ÐºÑ‚Ð¸Ð²Ð½Ð¾ÑÑ‚ÑŒ', twoFactorAuth: 'Ð”Ð²ÑƒÑ…Ñ„Ð°ÐºÑ‚Ð¾Ñ€Ð½Ð°Ñ Ð°ÑƒÑ‚ÐµÐ½Ñ‚Ð¸Ñ„Ð¸ÐºÐ°Ñ†Ð¸Ñ', twoFactorDesc: 'Ð—Ð°Ñ‰Ð¸Ñ‚Ð¸Ñ‚Ðµ Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚ Ð¿Ñ€Ð¸Ð»Ð¾Ð¶ÐµÐ½Ð¸ÐµÐ¼ Ð°ÑƒÑ‚ÐµÐ½Ñ‚Ð¸Ñ„Ð¸ÐºÐ°Ñ†Ð¸Ð¸', configure2FA: 'ÐÐ°ÑÑ‚Ñ€Ð¾Ð¸Ñ‚ÑŒ 2FA' },
  pagos: { title: 'ÐŸÐ»Ð°Ñ‚ÐµÐ¶Ð¸', send: 'ÐžÑ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ', history: 'Ð˜ÑÑ‚Ð¾Ñ€Ð¸Ñ', account: 'ÐÐºÐºÐ°ÑƒÐ½Ñ‚', recipient: 'ÐŸÐ¾Ð»ÑƒÑ‡Ð°Ñ‚ÐµÐ»ÑŒ', recipientPlaceholder: 'UUID Ð¿Ð¾Ð»ÑƒÑ‡Ð°Ñ‚ÐµÐ»Ñ', amount: 'Ð¡ÑƒÐ¼Ð¼Ð° (MXN)', concept: 'ÐžÐ¿Ð¸ÑÐ°Ð½Ð¸Ðµ (Ð½ÐµÐ¾Ð±ÑÐ·Ð°Ñ‚ÐµÐ»ÑŒÐ½Ð¾)', conceptPlaceholder: 'ÐÐ°Ð¿Ñ€: ÐžÐ¿Ð»Ð°Ñ‚Ð° Ð¾Ð±ÐµÐ´Ð°', paymentMethod: 'Ð¡Ð¿Ð¾ÑÐ¾Ð± Ð¾Ð¿Ð»Ð°Ñ‚Ñ‹', mercadoPago: 'Mercado Pago', oxxo: 'OXXO', sendAmount: 'ÐžÑ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ', processing: 'ÐžÐ±Ñ€Ð°Ð±Ð¾Ñ‚ÐºÐ°...', searchContact: 'ÐŸÐ¾Ð¸ÑÐº Ð¿Ð¾ Ð¸Ð¼ÐµÐ½Ð¸ Ð¸Ð»Ð¸ Ñ‚ÐµÐ»ÐµÑ„Ð¾Ð½Ñƒ...', minAmount: 'ÐœÐ¸Ð½Ð¸Ð¼ÑƒÐ¼: $10 MXN', maxAmount: 'ÐœÐ°ÐºÑÐ¸Ð¼ÑƒÐ¼: $500,000 MXN', maxOxxo: 'ÐœÐ°ÐºÑÐ¸Ð¼ÑƒÐ¼ OXXO: $10,000 MXN', selectRecipient: 'Ð’Ñ‹Ð±ÐµÑ€Ð¸Ñ‚Ðµ Ð¿Ð¾Ð»ÑƒÑ‡Ð°Ñ‚ÐµÐ»Ñ', loginFirst: 'Ð¡Ð½Ð°Ñ‡Ð°Ð»Ð° Ð²Ð¾Ð¹Ð´Ð¸Ñ‚Ðµ', pending: 'Ð’ Ð¾Ð¶Ð¸Ð´Ð°Ð½Ð¸Ð¸', approved: 'ÐžÐ´Ð¾Ð±Ñ€ÐµÐ½Ð¾', rejected: 'ÐžÑ‚ÐºÐ»Ð¾Ð½ÐµÐ½Ð¾', linkAccount: 'ÐŸÑ€Ð¸Ð²ÑÐ¶Ð¸Ñ‚Ðµ Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚', linkAccountDesc: 'ÐŸÑ€Ð¸Ð²ÑÐ¶Ð¸Ñ‚Ðµ Ð°ÐºÐºÐ°ÑƒÐ½Ñ‚ Ð´Ð»Ñ Ð¿Ð»Ð°Ñ‚ÐµÐ¶ÐµÐ¹', paymentSuccess: 'ÐŸÐ»Ð°Ñ‚Ñ‘Ð¶ ÑƒÑÐ¿ÐµÑˆÐµÐ½', sendAnother: 'ÐžÑ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ÑŒ ÐµÑ‰Ñ‘', biometricCancelled: 'Ð‘Ð¸Ð¾Ð¼ÐµÑ‚Ñ€Ð¸Ñ‡ÐµÑÐºÐ°Ñ Ð¿Ñ€Ð¾Ð²ÐµÑ€ÐºÐ° Ð¾Ñ‚Ð¼ÐµÐ½ÐµÐ½Ð°', noTransactions: 'Ð¢Ñ€Ð°Ð½Ð·Ð°ÐºÑ†Ð¸Ð¹ Ð¿Ð¾ÐºÐ° Ð½ÐµÑ‚' },
  seo: { title: 'MexiChat - Ð‘ÐµÐ·Ð¾Ð¿Ð°ÑÐ½Ñ‹Ð¹ Ð¼ÐµÑÑÐµÐ½Ð´Ð¶ÐµÑ€ Ñ Ð¿Ð»Ð°Ñ‚ÐµÐ¶Ð°Ð¼Ð¸ Ð¸ Ð±Ð¸Ð¾Ð¼ÐµÑ‚Ñ€Ð¸ÐµÐ¹', description: 'ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ð°Ñ Ð¿ÐµÑ€ÐµÐ¿Ð¸ÑÐºÐ° Ñ E2E ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸ÐµÐ¼, HD-Ð·Ð²Ð¾Ð½ÐºÐ¸, Mercado Pago, OXXO, Ð±Ð¸Ð¾Ð¼ÐµÑ‚Ñ€Ð¸Ñ, MexiVanza. Ð‘ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾.', keywords: 'mexichat, Ð¼ÐµÑÑÐµÐ½Ð´Ð¶ÐµÑ€, Ð¿Ñ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ð¹ Ñ‡Ð°Ñ‚, mercado pago, oxxo, Ð±Ð¸Ð¾Ð¼ÐµÑ‚Ñ€Ð¸Ñ, face id, ÑÐºÐ²Ð¾Ð·Ð½Ð¾Ðµ ÑˆÐ¸Ñ„Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ, mexivanza', ogTitle: 'MexiChat - ÐŸÑ€Ð¸Ð²Ð°Ñ‚Ð½Ñ‹Ð¹ Ð¼ÐµÑÑÐµÐ½Ð´Ð¶ÐµÑ€ Ñ Ð¿Ð»Ð°Ñ‚ÐµÐ¶Ð°Ð¼Ð¸', ogDescription: 'E2E Ñ‡Ð°Ñ‚, HD-Ð·Ð²Ð¾Ð½ÐºÐ¸, Mercado Pago/OXXO, Face ID, MexiVanza. Ð‘ÐµÑÐ¿Ð»Ð°Ñ‚Ð½Ð¾.' },
};
const zh: Translations = {
  common: { appName: 'MexiChat', loading: 'åŠ è½½ä¸­...', save: 'ä¿å­˜', cancel: 'å–æ¶ˆ', close: 'å…³é—­', delete: 'åˆ é™¤', confirm: 'ç¡®è®¤', back: 'è¿”å›ž', next: 'ä¸‹ä¸€æ­¥', search: 'æœç´¢', retry: 'é‡è¯•', error: 'é”™è¯¯', success: 'æˆåŠŸ', optional: 'å¯é€‰', select: 'é€‰æ‹©...' },
  home: { chats: 'èŠå¤©', groups: 'ç¾¤ç»„', payments: 'æ”¯ä»˜', community: 'ç¤¾åŒº', settings: 'è®¾ç½®' },
  landing: {
    nav: { features: 'åŠŸèƒ½', app: 'åº”ç”¨', privacy: 'éšç§', download: 'ä¸‹è½½', openApp: 'æ‰“å¼€åº”ç”¨' },
    hero: { badge: 'å¢¨è¥¿å“¥åˆ¶é€ ï¼Œé¢å‘ä¸–ç•Œ', line1: 'ä½ çš„ä¸–ç•Œï¼Œ', line2: 'ä½ çš„èŠå¤©ã€‚', subtitle: 'ç«¯åˆ°ç«¯åŠ å¯†ç§å¯†é€šè®¯ã€‚é«˜æ¸…é€šè¯ã€ç¾¤ç»„ã€Mercado Pagoå’ŒOXXOæ”¯ä»˜ã€ç”Ÿç‰©è¯†åˆ«è®¤è¯å’Œç¤¾åŒºâ€”â€”ä¸€ä¸ªåº”ç”¨å…¨æžå®šã€‚', downloadFree: 'å…è´¹ä¸‹è½½', openBrowser: 'åœ¨æµè§ˆå™¨ä¸­æ‰“å¼€', e2eEncryption: 'ç«¯åˆ°ç«¯åŠ å¯†', free: 'å…è´¹', noAds: 'æ— å¹¿å‘Š', platforms: 'å¹³å°' },
    screens: { title: 'äº†è§£MexiChat', subtitle: 'æ‚¨æ‰€éœ€çš„ä¸€åˆ‡ï¼Œå°½åœ¨ä¸€ä¸ªåº”ç”¨ä¸­' },
    features: {
      title: 'æ‚¨æ‰€éœ€çš„ä¸€åˆ‡', subtitle: 'ä¸–ç•Œçº§åŠŸèƒ½ï¼Œå¯¹æ‰€æœ‰äººå…è´¹',
      e2e: { title: 'ç«¯åˆ°ç«¯åŠ å¯†', desc: 'æ‰€æœ‰æ¶ˆæ¯å‡å—AES-256-GCMå’ŒECDH P-256å¯†é’¥ä¿æŠ¤ã€‚ä»»ä½•äººéƒ½æ— æ³•è¯»å–ã€‚' },
      calls: { title: 'é«˜æ¸…é€šè¯', desc: 'é«˜æ¸…è¯­éŸ³å’Œè§†é¢‘é€šè¯ï¼Œå®Œå…¨å…è´¹ã€‚æ— è®ºè·ç¦»å¤šè¿œéƒ½èƒ½è¿žæŽ¥ã€‚' },
      community: { title: 'MexiVanzaç¤¾åŒº', desc: 'é›†æˆç¤¾äº¤ç½‘ç»œï¼šåˆ†äº«å†…å®¹ï¼Œå‘çŽ°MexiMartï¼Œä¸Žå…¨çƒå¢¨è¥¿å“¥äººå»ºç«‹è”ç³»ã€‚' },
      payments: { title: 'å³æ—¶æ”¯ä»˜', desc: 'é€šè¿‡Mercado Pagoå’ŒOXXOç›´æŽ¥åœ¨èŠå¤©ä¸­æ”¶å‘æ¬¾é¡¹ã€‚å¿«é€Ÿã€å®‰å…¨ã€‚' },
      multiplatform: { title: 'å¤šå¹³å°', desc: 'Androidã€iOSå’ŒWebã€‚æ¶ˆæ¯åœ¨æ‰€æœ‰è®¾å¤‡ä¸Šè‡ªåŠ¨åŒæ­¥ã€‚' },
      biometric: { title: 'ç”Ÿç‰©è¯†åˆ«è®¤è¯', desc: 'ä½¿ç”¨Face IDã€Touch IDæˆ–æŒ‡çº¹ä¿æŠ¤è´¦æˆ·ã€‚æ”¯ä»˜å’Œåº”ç”¨è®¿é—®çš„ç”Ÿç‰©è¯†åˆ«éªŒè¯ã€‚' },
      oxxo: { title: 'OXXOæ”¯ä»˜', desc: 'åœ¨å¢¨è¥¿å“¥ä»»ä½•OXXOä¾¿åˆ©åº—ä»˜æ¬¾ã€‚å®‰å…¨åœ°å­˜å…¥çŽ°é‡‘ã€‚' },
      mercadoPago: { title: 'Mercado Pago', desc: 'é“¾æŽ¥Mercado Pagoè´¦æˆ·ï¼Œé€šè¿‡æ‹‰ä¸ç¾Žæ´²æœ€å¤§æ”¯ä»˜å¹³å°å³æ—¶æ”¶å‘æ¬¾é¡¹ã€‚' },
    },
    privacy: { title: 'æ‚¨çš„éšç§ï¼Œæˆ‘ä»¬çš„æ‰¿è¯º', desc: 'MexiChatä»¥éšç§ä¸ºä¼˜å…ˆè®¾è®¡ã€‚ç«¯åˆ°ç«¯åŠ å¯†æ‰€æœ‰æ¶ˆæ¯å’Œé€šè¯ã€‚æˆ‘ä»¬ä¸è¯»å–èŠå¤©ï¼Œä¸å‡ºå”®æ•°æ®ï¼Œä¸å±•ç¤ºå¹¿å‘Šã€‚', e2e: 'ç«¯åˆ°ç«¯åŠ å¯†', noTracking: 'æ— è¿½è¸ª', noAds: 'æ— å¹¿å‘Š', noDataSale: 'ä¸å‡ºå”®æ•°æ®' },
    download: { title: 'å…è´¹ä¸‹è½½MexiChat', subtitle: 'é€‚ç”¨äºŽæ‰€æœ‰è®¾å¤‡', android: 'Android', androidReq: 'Android 8.0+', ios: 'iOS', iosReq: 'iPhone iOS 15+', webApp: 'ç½‘é¡µåº”ç”¨', anyBrowser: 'ä»»ä½•æµè§ˆå™¨', openWebApp: 'æ‰“å¼€ç½‘é¡µåº”ç”¨', downloadApk: 'ç›´æŽ¥ä¸‹è½½APK' },
    footer: { tagline: 'å¢¨è¥¿å“¥çš„é€šè®¯å·¥å…·ï¼Œé¢å‘ä¸–ç•Œã€‚ç§å¯†ã€å®‰å…¨ã€æ°¸è¿œå…è´¹ã€‚', app: 'åº”ç”¨', features: 'åŠŸèƒ½', screenshots: 'æˆªå›¾', download: 'ä¸‹è½½', legal: 'æ³•å¾‹', privacyPolicy: 'éšç§æ”¿ç­–', terms: 'æœåŠ¡æ¡æ¬¾', community: 'ç¤¾åŒº', support: 'æ”¯æŒ', allRights: 'ç‰ˆæƒæ‰€æœ‰ã€‚', productOf: 'äº§å“æ¥è‡ª' },
    mockChat: { today: 'ä»Šå¤©', message: 'æ¶ˆæ¯...', online: 'åœ¨çº¿', locationShared: 'ä½ç½®å·²å…±äº«' },
  },
  mensajes: { directMessages: 'ç§ä¿¡', groups: 'ç¾¤ç»„', searchChats: 'æœç´¢èŠå¤©...', newChat: 'æ–°èŠå¤©', noMessages: 'æš‚æ— æ¶ˆæ¯', searchByUser: 'æŒ‰@ç”¨æˆ·åã€å§“åæˆ–ç”µè¯æœç´¢...', archived: 'å·²å½’æ¡£', hideArchived: 'éšè—å½’æ¡£', typeMessage: 'è¾“å…¥æ¶ˆæ¯...', encryptedNotice: 'æ‚¨çš„ç§äººæ¶ˆæ¯å·²åŠ å¯†ã€‚åªæœ‰æ‚¨å’ŒæŽ¥æ”¶è€…å¯ä»¥é˜…è¯»ã€‚', deleteConversation: 'åˆ é™¤å¯¹è¯', deleteConversationDesc: 'æ‰€æœ‰æ¶ˆæ¯å°†è¢«åˆ é™¤ã€‚æ— æ³•æ’¤é”€ã€‚', leaveGroup: 'é€€å‡ºç¾¤ç»„', leaveGroupDesc: 'æ‚¨å°†ä¸å†æ”¶åˆ°æ­¤ç¾¤ç»„æ¶ˆæ¯ã€‚', deleteGroup: 'åˆ é™¤ç¾¤ç»„', deleteGroupDesc: 'ç¾¤ç»„åŠæ¶ˆæ¯å°†è¢«æ°¸ä¹…åˆ é™¤ã€‚', kickMember: 'ç§»é™¤æˆå‘˜', kickMemberDesc: 'æ­¤ç”¨æˆ·å°†ä»Žç¾¤ç»„ä¸­ç§»é™¤ã€‚' },
  settings: { title: 'è®¾ç½®', profile: 'ä¸ªäººèµ„æ–™', privacy: 'éšç§', security: 'å®‰å…¨', appearance: 'å¤–è§‚', language: 'è¯­è¨€', fullName: 'å…¨å', username: 'ç”¨æˆ·å', phone: 'ç”µè¯', bio: 'ç®€ä»‹', bioPlaceholder: 'å†™ä¸€äº›å…³äºŽè‡ªå·±çš„ä¿¡æ¯...', nationality: 'å›½ç±', gender: 'æ€§åˆ«', changeAvatar: 'ç‚¹å‡»å›¾æ ‡æ›´æ¢ç…§ç‰‡', saving: 'ä¿å­˜ä¸­...', saveChanges: 'ä¿å­˜æ›´æ”¹', signOut: 'é€€å‡ºç™»å½•', lastSeen: 'æœ€åŽä¸Šçº¿', onlineStatus: 'åœ¨çº¿çŠ¶æ€', profilePhoto: 'å¤´åƒ', readReceipts: 'å·²è¯»å›žæ‰§', readReceiptsDesc: 'é˜…è¯»æ¶ˆæ¯æ—¶æ˜¾ç¤ºè“è‰²å¯¹å‹¾', everyone: 'æ‰€æœ‰äºº', contactsOnly: 'ä»…è”ç³»äºº', nobody: 'æ— äºº', pinLock: 'PINé”', pinConfigured: 'PINå·²è®¾ç½®ï¼ŒèŠå¤©å·²ä¿æŠ¤ã€‚', pinNotConfigured: 'ä½¿ç”¨PINç ä¿æŠ¤èŠå¤©ã€‚', lockNow: 'ç«‹å³é”å®š', removePin: 'ç§»é™¤PIN', setupPin: 'è®¾ç½®PIN', e2eEncryption: 'ç«¯åˆ°ç«¯åŠ å¯†', e2eDesc: 'ç§äººæ¶ˆæ¯å·²åŠ å¯†ã€‚åªæœ‰æ‚¨å’ŒæŽ¥æ”¶è€…å¯ä»¥é˜…è¯»ã€‚', activeSession: 'æ´»è·ƒä¼šè¯', browser: 'æµè§ˆå™¨', mobile: 'ç§»åŠ¨ç«¯', desktop: 'æ¡Œé¢ç«¯', lastActivity: 'ï¿½ï¿½åŽæ´»åŠ¨', twoFactorAuth: 'åŒå› ç´ è®¤è¯', twoFactorDesc: 'ä½¿ç”¨è®¤è¯åº”ç”¨ä¿æŠ¤è´¦æˆ·', configure2FA: 'è®¾ç½®2FA' },
  pagos: { title: 'æ”¯ä»˜', send: 'å‘é€', history: 'åŽ†å²', account: 'è´¦æˆ·', recipient: 'æ”¶æ¬¾äºº', recipientPlaceholder: 'æ”¶æ¬¾äººUUID', amount: 'é‡‘é¢ (MXN)', concept: 'å¤‡æ³¨ï¼ˆå¯é€‰ï¼‰', conceptPlaceholder: 'ä¾‹ï¼šåˆé¤è´¹ç”¨', paymentMethod: 'æ”¯ä»˜æ–¹å¼', mercadoPago: 'Mercado Pago', oxxo: 'OXXO', sendAmount: 'å‘é€', processing: 'å¤„ç†ä¸­...', searchContact: 'æŒ‰å§“åæˆ–ç”µè¯æœç´¢...', minAmount: 'æœ€ä½Žï¼š$10 MXN', maxAmount: 'æœ€é«˜ï¼š$500,000 MXN', maxOxxo: 'OXXOæœ€é«˜ï¼š$10,000 MXN', selectRecipient: 'è¯·é€‰æ‹©æ”¶æ¬¾äºº', loginFirst: 'è¯·å…ˆç™»å½•', pending: 'å¾…å¤„ç†', approved: 'å·²æ‰¹å‡†', rejected: 'å·²æ‹’ç»', linkAccount: 'å…³è”è´¦æˆ·', linkAccountDesc: 'å…³è”è´¦æˆ·ä»¥æ”¶å‘ä»˜æ¬¾', paymentSuccess: 'æ”¯ä»˜æˆåŠŸ', sendAnother: 'å†æ¬¡å‘é€', biometricCancelled: 'ç”Ÿç‰©è¯†åˆ«éªŒè¯å·²å–æ¶ˆ', noTransactions: 'æš‚æ— äº¤æ˜“è®°å½•' },
  seo: { title: 'MexiChat - å®‰å…¨é€šè®¯ï¼Œæ”¯æŒæ”¯ä»˜å’Œç”Ÿç‰©è¯†åˆ«', description: 'ç«¯åˆ°ç«¯åŠ å¯†ç§å¯†é€šè®¯ï¼Œé«˜æ¸…é€šè¯ï¼ŒMercado Pagoå’ŒOXXOæ”¯ä»˜ï¼Œç”Ÿç‰©è¯†åˆ«è®¤è¯ï¼ŒMexiVanzaç¤¾åŒºã€‚å…è´¹ã€‚', keywords: 'mexichat, å®‰å…¨é€šè®¯, ç§å¯†èŠå¤©, mercado pago, oxxo, ç”Ÿç‰©è¯†åˆ«, face id, ç«¯åˆ°ç«¯åŠ å¯†, mexivanza', ogTitle: 'MexiChat - æ”¯æŒæ”¯ä»˜å’Œç”Ÿç‰©è¯†åˆ«çš„ç§å¯†é€šè®¯', ogDescription: 'E2EåŠ å¯†èŠå¤©ï¼ŒMercado Pago/OXXOæ”¯ä»˜ï¼ŒFace ID/æŒ‡çº¹ï¼ŒMexiVanzaç¤¾åŒºã€‚å…è´¹ã€‚' },
};

const translations: Record<Language, Translations> = { es, en, ru, zh };
export default translations;

export function getTranslations(lang: Language): Translations {
  return translations[lang] || translations.es;
}