// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cchakgecusfybcokbmau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjaGFrZ2VjdXNmeWJjb2tibWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzOTA3NDksImV4cCI6MjA4Mzk2Njc0OX0.TWy1NmGHFDzBSJi3-z1k4f8_bkoxP94NPBUqOrGyGb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});